### ISSUE TITLE
Who were the collaborators on this project?

### ISSUE THREAD

**Issue by sdeddens** [Charlie-BR/best-damn-calculator#3]
Who were the collaborators on this project?  I really liked the style. Specifically which collaborator wrote the css.  The background was terrific.  Thanks  Deddens

**Comment by Charlie-BR** [comment]
Erich and I collab'ed on this project; I handled most of the HTML and CSS - glad you liked the minimalism Deddens!

**Comment by sdeddens** [comment]
Response received.
